### ISSUE TITLE
部署后无法访问，麻烦帮忙看一下。谢谢。

### ISSUE THREAD

**Issue by kugooer** [P3TERX/IBM-CF-V2#2]
配置成功
Vmess-ibm-clone(104***226:443)
启动服务(2020-09-11 09:38:01)...
V2Ray 4.27.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.14.6 windows/386)
A unified platform for anti-censorship.
2020/09/11 09:38:01 [Info] v2ray.com/core/common/platform/ctlcmd: <v2ctl message> 
v2ctl> Read config:  D:\Program Files\v2ray\config.json
2020/09/11 09:38:01 [Warning] v2ray.com/core: V2Ray 4.27.0 started
2020/09/11 09:38:02 tcp:127.0.0.1:62946 accepted tcp:alive.github.com:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62952 accepted tcp:i.ytimg.com:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62953 accepted tcp:yt3.ggpht.com:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62954 accepted tcp:www.youtube.com:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62947 accepted tcp:alive.github.com:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62955 accepted tcp:i.ytimg.com:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62956 accepted tcp:i.ytimg.com:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62957 accepted tcp:yt3.ggpht.com:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62958 accepted tcp:i.ytimg.com:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62959 accepted tcp:yt3.ggpht.com:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62942 accepted tcp:91.108.56.183:80 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62961 accepted tcp:91.108.56.183:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62962 accepted tcp:[2001:b28:f23f:f005::a]:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62963 accepted tcp:91.108.56.183:80 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62964 accepted tcp:i.ytimg.com:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62965 accepted tcp:i.ytimg.com:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62966 accepted tcp:yt3.ggpht.com:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62967 accepted tcp:yt3.ggpht.com:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62969 accepted tcp:yt3.ggpht.com:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62970 accepted tcp:www.youtube.com:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62971 accepted tcp:www.youtube.com:443 [proxy] 
2020/09/11 09:38:02 tcp:127.0.0.1:62972 accepted tcp:www.youtube.com:443 [proxy] 
2020/09/11 09:38:03 127.0.0.1:62974 accepted tcp:127.0.0.1:0 [api] 
2020/09/11 09:38:03 tcp:127.0.0.1:62975 accepted tcp:www.youtube.com:443 [proxy] 
2020/09/11 09:38:03 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2020/09/11 09:38:03 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2020/09/11 09:38:04 tcp:127.0.0.1:62977 accepted tcp:[2001:b28:f23f:f005::a]:443 [proxy] 
2020/09/11 09:38:04 tcp:127.0.0.1:62976 accepted tcp:91.108.56.183:443 [proxy] 
2020/09/11 09:38:04 tcp:127.0.0.1:62978 accepted tcp:91.108.56.183:80 [proxy] 
2020/09/11 09:38:04 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2020/09/11 09:38:04 tcp:127.0.0.1:62980 accepted tcp:www.youtube.com:443 [proxy] 
2020/09/11 09:38:04 tcp:127.0.0.1:62981 accepted tcp:yt3.ggpht.com:443 [proxy] 
2020/09/11 09:38:04 tcp:127.0.0.1:62982 accepted tcp:www.youtube.com:443 [proxy] 
2020/09/11 09:38:04 tcp:127.0.0.1:62985 accepted tcp:www.youtube.com:443 [proxy] 
2020/09/11 09:38:04 tcp:127.0.0.1:62983 accepted tcp:www.youtube.com:443 [proxy] 
2020/09/11 09:38:04 tcp:127.0.0.1:62984 accepted tcp:yt3.ggpht.com:443 [proxy] 
2020/09/11 09:38:04 tcp:127.0.0.1:62986 accepted tcp:yt3.ggpht.com:443 [proxy] 
2020/09/11 09:38:04 tcp:127.0.0.1:62988 accepted tcp:i.ytimg.com:443 [proxy] 
2020/09/11 09:38:04 tcp:127.0.0.1:62989 accepted tcp:i.ytimg.com:443 [proxy] 
2020/09/11 09:38:04 tcp:127.0.0.1:62991 accepted tcp:yt3.ggpht.com:443 [proxy] 
2020/09/11 09:38:04 tcp:127.0.0.1:62990 accepted tcp:i.ytimg.com:443 [proxy] 
2020/09/11 09:38:04 tcp:127.0.0.1:62992 accepted tcp:91.108.56.183:80 [proxy] 
2020/09/11 09:38:05 tcp:127.0.0.1:62993 accepted tcp:www.youtube.com:443 [proxy] 
2020/09/11 09:38:05 tcp:127.0.0.1:62994 accepted tcp:i.ytimg.com:443 [proxy] 
2020/09/11 09:38:05 tcp:127.0.0.1:62995 accepted tcp:yt3.ggpht.com:443 [proxy] 
2020/09/11 09:38:05 tcp:127.0.0.1:62996 accepted tcp:alive.github.com:443 [proxy] 
2020/09/11 09:38:05 tcp:127.0.0.1:62997 accepted tcp:alive.github.com:443 [proxy] 
2020/09/11 09:38:05 tcp:127.0.0.1:62998 accepted tcp:i.ytimg.com:443 [proxy] 
2020/09/11 09:38:05 tcp:127.0.0.1:62999 accepted tcp:i.ytimg.com:443 [proxy] 
2020/09/11 09:38:05 tcp:127.0.0.1:63000 accepted tcp:yt3.ggpht.com:443 [proxy] 
2020/09/11 09:38:05 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)

**Comment by P3TERX** [comment]
客户端要更新，协议是V **L** ESS。
